/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainLandingRouteRouteImport } from './routes/_main/_landing/route'
import { Route as MainAuthRouteRouteImport } from './routes/_main/_auth/route'
import { Route as MainLandingIndexRouteImport } from './routes/_main/_landing/index'
import { Route as MainLandingTermsRouteImport } from './routes/_main/_landing/terms'
import { Route as MainLandingSignupRouteImport } from './routes/_main/_landing/signup'
import { Route as MainLandingPrivacyRouteImport } from './routes/_main/_landing/privacy'
import { Route as MainLandingLoginRouteImport } from './routes/_main/_landing/login'
import { Route as MainAuthProfileRouteImport } from './routes/_main/_auth/profile'
import { Route as MainAuthConversationsRouteRouteImport } from './routes/_main/_auth/conversations/route'
import { Route as MainAuthConversationsIndexRouteImport } from './routes/_main/_auth/conversations/index'
import { Route as MainAuthConversationsIdIndexRouteImport } from './routes/_main/_auth/conversations/$id/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLandingRouteRoute = MainLandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLandingIndexRoute = MainLandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingTermsRoute = MainLandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingSignupRoute = MainLandingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingPrivacyRoute = MainLandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingLoginRoute = MainLandingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainAuthProfileRoute = MainAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthConversationsRouteRoute =
  MainAuthConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => MainAuthRouteRoute,
  } as any)
const MainAuthConversationsIndexRoute =
  MainAuthConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAuthConversationsRouteRoute,
  } as any)
const MainAuthConversationsIdIndexRoute =
  MainAuthConversationsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => MainAuthConversationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLandingIndexRoute
  '/logout': typeof LogoutRoute
  '/conversations': typeof MainAuthConversationsRouteRouteWithChildren
  '/profile': typeof MainAuthProfileRoute
  '/login': typeof MainLandingLoginRoute
  '/privacy': typeof MainLandingPrivacyRoute
  '/signup': typeof MainLandingSignupRoute
  '/terms': typeof MainLandingTermsRoute
  '/conversations/': typeof MainAuthConversationsIndexRoute
  '/conversations/$id/': typeof MainAuthConversationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLandingIndexRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof MainAuthProfileRoute
  '/login': typeof MainLandingLoginRoute
  '/privacy': typeof MainLandingPrivacyRoute
  '/signup': typeof MainLandingSignupRoute
  '/terms': typeof MainLandingTermsRoute
  '/conversations': typeof MainAuthConversationsIndexRoute
  '/conversations/$id': typeof MainAuthConversationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_main/_auth': typeof MainAuthRouteRouteWithChildren
  '/_main/_landing': typeof MainLandingRouteRouteWithChildren
  '/_main/_auth/conversations': typeof MainAuthConversationsRouteRouteWithChildren
  '/_main/_auth/profile': typeof MainAuthProfileRoute
  '/_main/_landing/login': typeof MainLandingLoginRoute
  '/_main/_landing/privacy': typeof MainLandingPrivacyRoute
  '/_main/_landing/signup': typeof MainLandingSignupRoute
  '/_main/_landing/terms': typeof MainLandingTermsRoute
  '/_main/_landing/': typeof MainLandingIndexRoute
  '/_main/_auth/conversations/': typeof MainAuthConversationsIndexRoute
  '/_main/_auth/conversations/$id/': typeof MainAuthConversationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/conversations'
    | '/profile'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/conversations/'
    | '/conversations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/profile'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/conversations'
    | '/conversations/$id'
  id:
    | '__root__'
    | '/_main'
    | '/logout'
    | '/_main/_auth'
    | '/_main/_landing'
    | '/_main/_auth/conversations'
    | '/_main/_auth/profile'
    | '/_main/_landing/login'
    | '/_main/_landing/privacy'
    | '/_main/_landing/signup'
    | '/_main/_landing/terms'
    | '/_main/_landing/'
    | '/_main/_auth/conversations/'
    | '/_main/_auth/conversations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_landing': {
      id: '/_main/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLandingRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_auth': {
      id: '/_main/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_landing/': {
      id: '/_main/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLandingIndexRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/terms': {
      id: '/_main/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainLandingTermsRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/signup': {
      id: '/_main/_landing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainLandingSignupRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/privacy': {
      id: '/_main/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainLandingPrivacyRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/login': {
      id: '/_main/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLandingLoginRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_auth/profile': {
      id: '/_main/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainAuthProfileRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/conversations': {
      id: '/_main/_auth/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof MainAuthConversationsRouteRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/conversations/': {
      id: '/_main/_auth/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof MainAuthConversationsIndexRouteImport
      parentRoute: typeof MainAuthConversationsRouteRoute
    }
    '/_main/_auth/conversations/$id/': {
      id: '/_main/_auth/conversations/$id/'
      path: '/$id'
      fullPath: '/conversations/$id/'
      preLoaderRoute: typeof MainAuthConversationsIdIndexRouteImport
      parentRoute: typeof MainAuthConversationsRouteRoute
    }
  }
}

interface MainAuthConversationsRouteRouteChildren {
  MainAuthConversationsIndexRoute: typeof MainAuthConversationsIndexRoute
  MainAuthConversationsIdIndexRoute: typeof MainAuthConversationsIdIndexRoute
}

const MainAuthConversationsRouteRouteChildren: MainAuthConversationsRouteRouteChildren =
  {
    MainAuthConversationsIndexRoute: MainAuthConversationsIndexRoute,
    MainAuthConversationsIdIndexRoute: MainAuthConversationsIdIndexRoute,
  }

const MainAuthConversationsRouteRouteWithChildren =
  MainAuthConversationsRouteRoute._addFileChildren(
    MainAuthConversationsRouteRouteChildren,
  )

interface MainAuthRouteRouteChildren {
  MainAuthConversationsRouteRoute: typeof MainAuthConversationsRouteRouteWithChildren
  MainAuthProfileRoute: typeof MainAuthProfileRoute
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthConversationsRouteRoute: MainAuthConversationsRouteRouteWithChildren,
  MainAuthProfileRoute: MainAuthProfileRoute,
}

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
)

interface MainLandingRouteRouteChildren {
  MainLandingLoginRoute: typeof MainLandingLoginRoute
  MainLandingPrivacyRoute: typeof MainLandingPrivacyRoute
  MainLandingSignupRoute: typeof MainLandingSignupRoute
  MainLandingTermsRoute: typeof MainLandingTermsRoute
  MainLandingIndexRoute: typeof MainLandingIndexRoute
}

const MainLandingRouteRouteChildren: MainLandingRouteRouteChildren = {
  MainLandingLoginRoute: MainLandingLoginRoute,
  MainLandingPrivacyRoute: MainLandingPrivacyRoute,
  MainLandingSignupRoute: MainLandingSignupRoute,
  MainLandingTermsRoute: MainLandingTermsRoute,
  MainLandingIndexRoute: MainLandingIndexRoute,
}

const MainLandingRouteRouteWithChildren =
  MainLandingRouteRoute._addFileChildren(MainLandingRouteRouteChildren)

interface MainRouteRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren
  MainLandingRouteRoute: typeof MainLandingRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainLandingRouteRoute: MainLandingRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
