/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MusicResolveRouteImport } from './routes/music.resolve'
import { Route as MainLandingRouteRouteImport } from './routes/_main/_landing/route'
import { Route as MainAuthRouteRouteImport } from './routes/_main/_auth/route'
import { Route as MainLandingIndexRouteImport } from './routes/_main/_landing/index'
import { Route as MainLandingTermsRouteImport } from './routes/_main/_landing/terms'
import { Route as MainLandingSignupRouteImport } from './routes/_main/_landing/signup'
import { Route as MainLandingPrivacyRouteImport } from './routes/_main/_landing/privacy'
import { Route as MainLandingLoginRouteImport } from './routes/_main/_landing/login'
import { Route as MainAuthGuardedRouteRouteImport } from './routes/_main/_auth/_guarded/route'
import { Route as MainAuthSTokenRouteImport } from './routes/_main/_auth/s/$token'
import { Route as MainAuthGuardedProfileRouteImport } from './routes/_main/_auth/_guarded/profile'
import { Route as MainAuthGuardedConversationsRouteRouteImport } from './routes/_main/_auth/_guarded/conversations/route'
import { Route as MainAuthGuardedConversationsIndexRouteImport } from './routes/_main/_auth/_guarded/conversations/index'
import { Route as MainAuthGuardedConversationsIdIndexRouteImport } from './routes/_main/_auth/_guarded/conversations/$id/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicResolveRoute = MusicResolveRouteImport.update({
  id: '/music/resolve',
  path: '/music/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLandingRouteRoute = MainLandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLandingIndexRoute = MainLandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingTermsRoute = MainLandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingSignupRoute = MainLandingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingPrivacyRoute = MainLandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainLandingLoginRoute = MainLandingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainLandingRouteRoute,
} as any)
const MainAuthGuardedRouteRoute = MainAuthGuardedRouteRouteImport.update({
  id: '/_guarded',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthSTokenRoute = MainAuthSTokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthGuardedProfileRoute = MainAuthGuardedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainAuthGuardedRouteRoute,
} as any)
const MainAuthGuardedConversationsRouteRoute =
  MainAuthGuardedConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => MainAuthGuardedRouteRoute,
  } as any)
const MainAuthGuardedConversationsIndexRoute =
  MainAuthGuardedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainAuthGuardedConversationsRouteRoute,
  } as any)
const MainAuthGuardedConversationsIdIndexRoute =
  MainAuthGuardedConversationsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => MainAuthGuardedConversationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLandingIndexRoute
  '/logout': typeof LogoutRoute
  '/music/resolve': typeof MusicResolveRoute
  '/login': typeof MainLandingLoginRoute
  '/privacy': typeof MainLandingPrivacyRoute
  '/signup': typeof MainLandingSignupRoute
  '/terms': typeof MainLandingTermsRoute
  '/conversations': typeof MainAuthGuardedConversationsRouteRouteWithChildren
  '/profile': typeof MainAuthGuardedProfileRoute
  '/s/$token': typeof MainAuthSTokenRoute
  '/conversations/': typeof MainAuthGuardedConversationsIndexRoute
  '/conversations/$id/': typeof MainAuthGuardedConversationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLandingIndexRoute
  '/logout': typeof LogoutRoute
  '/music/resolve': typeof MusicResolveRoute
  '/login': typeof MainLandingLoginRoute
  '/privacy': typeof MainLandingPrivacyRoute
  '/signup': typeof MainLandingSignupRoute
  '/terms': typeof MainLandingTermsRoute
  '/profile': typeof MainAuthGuardedProfileRoute
  '/s/$token': typeof MainAuthSTokenRoute
  '/conversations': typeof MainAuthGuardedConversationsIndexRoute
  '/conversations/$id': typeof MainAuthGuardedConversationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_main/_auth': typeof MainAuthRouteRouteWithChildren
  '/_main/_landing': typeof MainLandingRouteRouteWithChildren
  '/music/resolve': typeof MusicResolveRoute
  '/_main/_auth/_guarded': typeof MainAuthGuardedRouteRouteWithChildren
  '/_main/_landing/login': typeof MainLandingLoginRoute
  '/_main/_landing/privacy': typeof MainLandingPrivacyRoute
  '/_main/_landing/signup': typeof MainLandingSignupRoute
  '/_main/_landing/terms': typeof MainLandingTermsRoute
  '/_main/_landing/': typeof MainLandingIndexRoute
  '/_main/_auth/_guarded/conversations': typeof MainAuthGuardedConversationsRouteRouteWithChildren
  '/_main/_auth/_guarded/profile': typeof MainAuthGuardedProfileRoute
  '/_main/_auth/s/$token': typeof MainAuthSTokenRoute
  '/_main/_auth/_guarded/conversations/': typeof MainAuthGuardedConversationsIndexRoute
  '/_main/_auth/_guarded/conversations/$id/': typeof MainAuthGuardedConversationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/music/resolve'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/conversations'
    | '/profile'
    | '/s/$token'
    | '/conversations/'
    | '/conversations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/music/resolve'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/profile'
    | '/s/$token'
    | '/conversations'
    | '/conversations/$id'
  id:
    | '__root__'
    | '/_main'
    | '/logout'
    | '/_main/_auth'
    | '/_main/_landing'
    | '/music/resolve'
    | '/_main/_auth/_guarded'
    | '/_main/_landing/login'
    | '/_main/_landing/privacy'
    | '/_main/_landing/signup'
    | '/_main/_landing/terms'
    | '/_main/_landing/'
    | '/_main/_auth/_guarded/conversations'
    | '/_main/_auth/_guarded/profile'
    | '/_main/_auth/s/$token'
    | '/_main/_auth/_guarded/conversations/'
    | '/_main/_auth/_guarded/conversations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  MusicResolveRoute: typeof MusicResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/resolve': {
      id: '/music/resolve'
      path: '/music/resolve'
      fullPath: '/music/resolve'
      preLoaderRoute: typeof MusicResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_landing': {
      id: '/_main/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLandingRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_auth': {
      id: '/_main/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_landing/': {
      id: '/_main/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLandingIndexRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/terms': {
      id: '/_main/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainLandingTermsRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/signup': {
      id: '/_main/_landing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainLandingSignupRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/privacy': {
      id: '/_main/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainLandingPrivacyRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_landing/login': {
      id: '/_main/_landing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLandingLoginRouteImport
      parentRoute: typeof MainLandingRouteRoute
    }
    '/_main/_auth/_guarded': {
      id: '/_main/_auth/_guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthGuardedRouteRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/s/$token': {
      id: '/_main/_auth/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof MainAuthSTokenRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/_guarded/profile': {
      id: '/_main/_auth/_guarded/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainAuthGuardedProfileRouteImport
      parentRoute: typeof MainAuthGuardedRouteRoute
    }
    '/_main/_auth/_guarded/conversations': {
      id: '/_main/_auth/_guarded/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof MainAuthGuardedConversationsRouteRouteImport
      parentRoute: typeof MainAuthGuardedRouteRoute
    }
    '/_main/_auth/_guarded/conversations/': {
      id: '/_main/_auth/_guarded/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof MainAuthGuardedConversationsIndexRouteImport
      parentRoute: typeof MainAuthGuardedConversationsRouteRoute
    }
    '/_main/_auth/_guarded/conversations/$id/': {
      id: '/_main/_auth/_guarded/conversations/$id/'
      path: '/$id'
      fullPath: '/conversations/$id/'
      preLoaderRoute: typeof MainAuthGuardedConversationsIdIndexRouteImport
      parentRoute: typeof MainAuthGuardedConversationsRouteRoute
    }
  }
}

interface MainAuthGuardedConversationsRouteRouteChildren {
  MainAuthGuardedConversationsIndexRoute: typeof MainAuthGuardedConversationsIndexRoute
  MainAuthGuardedConversationsIdIndexRoute: typeof MainAuthGuardedConversationsIdIndexRoute
}

const MainAuthGuardedConversationsRouteRouteChildren: MainAuthGuardedConversationsRouteRouteChildren =
  {
    MainAuthGuardedConversationsIndexRoute:
      MainAuthGuardedConversationsIndexRoute,
    MainAuthGuardedConversationsIdIndexRoute:
      MainAuthGuardedConversationsIdIndexRoute,
  }

const MainAuthGuardedConversationsRouteRouteWithChildren =
  MainAuthGuardedConversationsRouteRoute._addFileChildren(
    MainAuthGuardedConversationsRouteRouteChildren,
  )

interface MainAuthGuardedRouteRouteChildren {
  MainAuthGuardedConversationsRouteRoute: typeof MainAuthGuardedConversationsRouteRouteWithChildren
  MainAuthGuardedProfileRoute: typeof MainAuthGuardedProfileRoute
}

const MainAuthGuardedRouteRouteChildren: MainAuthGuardedRouteRouteChildren = {
  MainAuthGuardedConversationsRouteRoute:
    MainAuthGuardedConversationsRouteRouteWithChildren,
  MainAuthGuardedProfileRoute: MainAuthGuardedProfileRoute,
}

const MainAuthGuardedRouteRouteWithChildren =
  MainAuthGuardedRouteRoute._addFileChildren(MainAuthGuardedRouteRouteChildren)

interface MainAuthRouteRouteChildren {
  MainAuthGuardedRouteRoute: typeof MainAuthGuardedRouteRouteWithChildren
  MainAuthSTokenRoute: typeof MainAuthSTokenRoute
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthGuardedRouteRoute: MainAuthGuardedRouteRouteWithChildren,
  MainAuthSTokenRoute: MainAuthSTokenRoute,
}

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
)

interface MainLandingRouteRouteChildren {
  MainLandingLoginRoute: typeof MainLandingLoginRoute
  MainLandingPrivacyRoute: typeof MainLandingPrivacyRoute
  MainLandingSignupRoute: typeof MainLandingSignupRoute
  MainLandingTermsRoute: typeof MainLandingTermsRoute
  MainLandingIndexRoute: typeof MainLandingIndexRoute
}

const MainLandingRouteRouteChildren: MainLandingRouteRouteChildren = {
  MainLandingLoginRoute: MainLandingLoginRoute,
  MainLandingPrivacyRoute: MainLandingPrivacyRoute,
  MainLandingSignupRoute: MainLandingSignupRoute,
  MainLandingTermsRoute: MainLandingTermsRoute,
  MainLandingIndexRoute: MainLandingIndexRoute,
}

const MainLandingRouteRouteWithChildren =
  MainLandingRouteRoute._addFileChildren(MainLandingRouteRouteChildren)

interface MainRouteRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren
  MainLandingRouteRoute: typeof MainLandingRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainLandingRouteRoute: MainLandingRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  MusicResolveRoute: MusicResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
